/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/Vuc2uhVhuIR
 */
import { AvatarImage, AvatarFallback, Avatar } from "@/components/ui/avatar"
import { CardTitle, CardDescription, CardHeader, CardContent, Card } from "@/components/ui/card"
import { Calendar } from "@/components/ui/calendar"
import { Button } from "@/components/ui/button"
import { ScrollArea } from "@/components/ui/scroll-area"
// import { ResponsiveBar } from "@nivo/bar"
// import { ResponsiveLine } from "@nivo/line"
// import Link from "next/link"
import { ResponsiveHeatMap } from "@nivo/heatmap"
import { ResponsiveLine } from "@nivo/line"
import { ResponsiveBar } from "@nivo/bar"
import { TableHead, TableRow, TableHeader, TableCell, TableBody, Table } from "@/components/ui/table"
import { Swiper, SwiperSlide } from 'swiper/react';

// Import Swiper styles
import 'swiper/css';
import 'swiper/css/navigation';
import { Navigation } from 'swiper/modules';
import './Studentui.css'
import Dropdown from "./dropdown"



export default function Studentui() {
  
  
  
  return (
    (<div className="flex flex-col h-screen bg-gray-100 dark:bg-gray-800">
      <header
        className="flex items-center h-16 px-4 bg-[#F0EDFF] border-b dark:bg-gray-900">
        <nav className="flex items-center justify-between w-full">
          <div className="flex items-center space-x-4">
            <LayoutDashboardIcon className="w-6 h-6" />
            <span className="text-xl font-bold">Student Dashboard</span>
          </div>
          <Avatar className="h-9 w-9">
            <AvatarImage alt="User avatar" src="https://imgs.search.brave.com/J0ixr3aHGA8aitBrET8u4exc5KcrQl8PWXGrvAdsUY4/rs:fit:500:0:0/g:ce/aHR0cHM6Ly9mcmVl/c3ZnLm9yZy9pbWcv/YWJzdHJhY3QtdXNl/ci1mbGF0LTQucG5n" />
            {/* <AvatarFallback>JD</AvatarFallback> */}
          </Avatar>
        </nav>
      </header>
      <div className="flex flex-1 overflow-hidden">
        <aside className="p-4 bg-[#111129] border-r w-60 dark:bg-gray-900 text-[#00C893]">
          <nav className="space-y-2">
            <a 
              className="block px-3 py-2 rounded hover:bg-gray-200 hover:text-[#191929] dark:hover:bg-gray-700"
              href="#studentdetails"
              
              >
              Student Details
            </a>
            
            <a
              className="block px-3 py-2 rounded hover:bg-gray-200 hover:text-[#191929] dark:hover:bg-gray-700"
              href="#completedcourses"
              
              >
              Completed Courses
            </a>
            
            <a
              className="block px-3 py-2 rounded hover:bg-gray-200 hover:text-[#191929] dark:hover:bg-gray-700"
              href="#upcomingassessments">
              Upcoming Assessments
            </a>
             
                 
           
            <a
              className="block px-3 py-2 rounded hover:bg-gray-200 hover:text-[#191929] dark:hover:bg-gray-700"
              href="#analyticsboard">
              Analytics Board
            </a>
            
            <a
              className="block px-3 py-2 rounded hover:bg-gray-200 hover:text-[#191929] dark:hover:bg-gray-700"
              href="#leaderboard">
              Leaderboard
            </a>
            
          </nav>
        </aside>
        <main className="flex-1 p-4 overflow-auto bg-[#111129] text-white">
          <section className="mb-8" id="studentdetails">
            <h2 className="mb-2 text-2xl font-bold">Student Details</h2>
            
            <div className="grid grid-cols-1 gap-2 md:grid-cols-2">
            <Card className="p-2 bg-[#F0EDFF] shadow-lg flex justify-between items-center">
              <div>
              <CardHeader>
                <CardTitle>Mohammad Kaif</CardTitle>
              </CardHeader>
              <CardContent>
                <div className="grid gap-1">
                  <div><span className="text-[#111129] font-bold">Registered ID</span>: CS102</div>
                  <div><span className="text-[#111129] font-bold">Mail ID</span>: kaifata31@gmail.com</div>
                </div>
              </CardContent>
              </div>
              <div className="w-[100px] h-[100px] mx-20">
                <img  src="https://imgs.search.brave.com/J0ixr3aHGA8aitBrET8u4exc5KcrQl8PWXGrvAdsUY4/rs:fit:500:0:0/g:ce/aHR0cHM6Ly9mcmVl/c3ZnLm9yZy9pbWcv/YWJzdHJhY3QtdXNl/ci1mbGF0LTQucG5n" alt="" />
              </div>
             
            </Card>
           
            
          </div>

          </section>

          <section className="mb-8" id="completedcourses">
            <h2 className="mb-2 text-2xl font-bold">Class Rooms</h2>

           
      <Swiper navigation={true} modules={[Navigation]} className="mySwiper"
       slidesPerView={3}
       spaceBetween={30}
       
      >
        <SwiperSlide className=" rounded-[50px]">
            <Card className="p-4 bg-[#F0EDFF] shadow-lg w-[100%] rounded-[30px]">
              <CardHeader>
                <CardTitle>Mathematics</CardTitle>
                <CardDescription>Go through class</CardDescription>
              </CardHeader>
              <Button className="mt-4 bg-[#00C893] text-white hover:bg-black hover:text-white">View Details</Button>
            </Card>
        </SwiperSlide>
        <SwiperSlide className=" rounded-[50px]">
            <Card className="p-4 bg-[#F0EDFF] shadow-lg w-[100%] rounded-[30px]">
              <CardHeader>
                <CardTitle>Digital Logic Design</CardTitle>
                <CardDescription>Go through class</CardDescription>
              </CardHeader>
              <Button className="mt-4 bg-[#00C893] text-white">View Details</Button>
            </Card>
        </SwiperSlide>
         
      </Swiper>

          </section>
          <section className="mb-8" id="upcomingassessments" >
            <h2 className="mb-2 text-2xl font-bold">Upcoming Assessments</h2>
           
           
      <Swiper navigation={true} modules={[Navigation]} className="mySwiper"
       slidesPerView={3}
       spaceBetween={30}
       
      >
        <SwiperSlide className=" rounded-[50px]">
          <Card className="p-4 bg-[#F0EDFF]  shadow-lg w-[100%] rounded-[30px]">
              <CardHeader>
                <CardTitle>LCM and HCF</CardTitle>
                <CardDescription>Duration: 1 hour</CardDescription>
              </CardHeader>
              <br></br>
              <Button className="mt-4 bg-[#00C893] text-white">Start</Button>
            </Card>
        </SwiperSlide>
        <SwiperSlide className=" rounded-[50px]">
          <Card className="p-4 bg-[#F0EDFF] shadow-lg w-[100%] rounded-[30px]">
              <CardHeader>
                <CardTitle>Linear Equations</CardTitle>
                <CardDescription>Duration: 1 hour</CardDescription>
              </CardHeader>
              <br></br>
              <Button className="mt-4 bg-[#00C893] text-white">Start</Button>
            </Card>
        </SwiperSlide>
        <SwiperSlide className=" rounded-[50px]">
          <Card className="p-4 bg-[#F0EDFF] shadow-lg w-[100%] rounded-[30px]">
              <CardHeader>
                <CardTitle>Analog to Digital Conversions</CardTitle>
                <CardDescription>Duration: 1 hour</CardDescription>
              </CardHeader>
              <br></br>
              <Button className="mt-4 bg-[#00C893] text-white">Start</Button>
            </Card>
        </SwiperSlide>
        <SwiperSlide className=" rounded-[50px]">
          <Card className="p-4 bg-[#F0EDFF] shadow-lg w-[100%] rounded-[30px]">
              <CardHeader>
                <CardTitle>Flipflops</CardTitle>
                <CardDescription>Duration: 1 hour</CardDescription>
              </CardHeader>
              <br></br>
              <Button className="mt-4 bg-[#00C893] text-white">Start</Button>
            </Card>
        </SwiperSlide>
       
        
      </Swiper>

            </section>

         

          <section className="mb-6" id="analyticsboard">
          <div className="flex gap-9">
            <h2 className="mb-2 text-2xl font-bold">Analytics Board</h2>
          
            <Dropdown/>
          </div>
         
          
          <br/>
          <div className="grid grid-cols-1 gap-4 md:grid-cols-2 ">
            
            <LineChart className="w-full h-[300px]" />
          </div>
        </section>
           
          <section className="mb-8" id="leaderboard">
          <div className="flex gap-9">
            <h2 className="mb-2 text-2xl font-bold">Leader Board</h2>
          
            <Dropdown/>
          </div>
          <br/>
            <Table>
              <TableHeader>
                <TableRow className="bg-[#F0EDFF]">
                  <TableHead className="text-[#111129]">Rank</TableHead>
                  <TableHead className="text-[#111129]">Name</TableHead>
                  <TableHead className="text-right text-[#111129]">Score</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody className="bg-[#000] text-white">
                <TableRow>
                  <TableCell>1</TableCell>
                  <TableCell>John deep</TableCell>
                  <TableCell className="text-right">100</TableCell>
                </TableRow>
                <TableRow>
                  <TableCell>2</TableCell>
                  <TableCell>John paul</TableCell>
                  <TableCell className="text-right">90</TableCell>
                </TableRow>
                <TableRow>
                  <TableCell>3</TableCell>
                  <TableCell>Bob smith </TableCell>
                  <TableCell className="text-right">80</TableCell>
                </TableRow>
              </TableBody>
            </Table>
            <Button className="mt-4 bg-[#00C893] text-white mx-auto md:ml-auto">View More</Button>
          </section>
        </main>
      </div>
    </div>)
  );
}


function LayoutDashboardIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <rect width="7" height="9" x="3" y="3" rx="1" />
      <rect width="7" height="5" x="14" y="3" rx="1" />
      <rect width="7" height="9" x="14" y="12" rx="1" />
      <rect width="7" height="5" x="3" y="16" rx="1" />
    </svg>)
  );
}


// function BarChart(props) {
//   return (
//     (<div {...props}>
//       <ResponsiveBar
//         data={[
//           { name: "Week1", count: 111 },
//           { name: "Week2", count: 157 },
//           { name: "Week3", count: 129 },
//           { name: "Week4", count: 150 },
//         ]}
//         keys={["count"]}
//         indexBy="name"
//         margin={{ top: 0, right: 0, bottom: 40, left: 40 }}
//         padding={0.3}
//         colors={["#2563eb"]}
//         axisBottom={{
//           tickSize: 0,
//           tickPadding: 16,
//         }}
//         axisLeft={{
//           tickSize: 0,
//           tickValues: 4,
//           tickPadding: 16,
//         }}
//         gridYValues={4}
//         theme={{
//           tooltip: {
//             chip: {
//               borderRadius: "9999px",
//             },
//             container: {
//               fontSize: "12px",
//               textTransform: "capitalize",
//               borderRadius: "6px",
//             },
//           },
//           grid: {
//             line: {
//               stroke: "#f3f4f6",
//             },
//           },
//         }}
//         tooltipLabel={({ id }) => `${id}`}
//         enableLabel={false}
//         role="application"
//         ariaLabel="A bar chart showing data" />
//     </div>)
//   );
// }


function LineChart(props) {
  return (
    (<div {...props}>
      <ResponsiveLine
        data={[
          {
            id: "Desktop",
            data: [
              { x: "Jan", y: 43 },
              { x: "Feb", y: 137 },
              { x: "Mar", y: 61 },
              { x: "Apr", y: 145 },
              { x: "May", y: 26 },
              { x: "Jun", y: 154 },
            ],
          },
          // {
          //   id: "Mobile",
          //   data: [
          //     { x: "Jan", y: 60 },
          //     { x: "Feb", y: 48 },
          //     { x: "Mar", y: 177 },
          //     { x: "Apr", y: 78 },
          //     { x: "May", y: 96 },
          //     { x: "Jun", y: 204 },
          //   ],
          // },
        ]}
        margin={{ top: 10, right: 10, bottom: 40, left: 40 }}
        xScale={{
          type: "point",
        }}
        yScale={{
          type: "linear",
        }}
        axisTop={null}
        axisRight={null}
        axisBottom={{
          tickSize: 0,
          tickPadding: 16,
        }}
        axisLeft={{
          tickSize: 0,
          tickValues: 5,
          tickPadding: 16,
        }}
        colors={["#1DE48D", ""]}
        pointSize={6}
        useMesh={true}
        gridYValues={6}
        theme={{
          tooltip: {
            chip: {
              borderRadius: "9999px",
            },
            container: {
              fontSize: "12px",
              textTransform: "capitalize",
              borderRadius: "6px",
            },
          },
          grid: {
            line: {
              stroke: "#f3f4f6",
            },
          },
        }}
        role="application" />
    </div>)
  );
}
